### ISSUE TITLE
False/Postives on open-port detection

### ISSUE THREAD

**Issue by n3rmix** [guardicore/labs_campaigns#6]
Just a small one:

`netstat -ano | grep LISTEN | grep 1234`

would also detect other open ports from othe processes like postfix running on 12346.
maybe would be better to use grep with "-w" option, to select only those lines containing matches that form whole word.

**Comment by andrewbates09** [comment]
I had the same thought with https://github.com/guardicore/labs_campaigns/pull/8

**Comment by NateCrawford** [comment]
Would this be sufficient? 
netstat -lno | grep ":1234 "

**Comment by joerosato** [comment]
Just change

`if [[ $(netstat -ano | grep LISTEN | grep 1234) ]]; then
`
to

`if [[ $(netstat -ano | grep LISTEN | grep -w 1234) ]]; then
`

for me it found port 41234, this forces it to look at words.

**Comment by pellucida** [comment]
I picked up a unix domain socket with 1234 in its path.

netstat -A inet,inet6 -l -n -t 
might be a better option (and with -t if its only tcp being used.)

I used grep -E -e ':\<1234\>'  for the word pattern.

If lsof is installed its probably a better option.

**Comment by ophirharpazg** [comment]
Solved in [this PR](https://github.com/guardicore/labs_campaigns/pull/12/files).
Thanks for pointing out!
